### PR TITLE
Correct the ordering of after hooks for Jest 20.

### PR DESCRIPTION
**Pull request by gdborton**
The logic for running the after hooks included a work around for a bug that
existed in Jest 18 and 19.  The bug has since been fixed in Jest 20, so we're
removing the fix.  Because removing the workaround will break 18 and 19, this
is a breaking change, and as such I've dropped 18/19 references from
package.json and updated to 20 everywhere.

**Note:** I'm operating on the assumption that you'd prefer a breaking change
rather than attempting to have a logic switch based on the Jest version.  Let me
know if you'd rather attempt to continue supporting 18+.

**NoteNote:** Jest 20.0.0 is currently broken for npm@2 and requires manual
installation of `ansi-regex` and `jest-matcher-utils`. The Jest team is aware of
this and will be fixing in the next patch. I think this can wait until that lands.

### CODE REVIEW

**Comment by ljharb** [comment]
> Let me know if you'd rather attempt to continue supporting 18+.

I'd be very interested to see what that PR looks like; it'd be ideal to add v20 support in a minor instead of a major.

> I think this can wait until that lands.

I agree; we shouldn't support 20.0.0 at all, and should start v20 support at the first one that works with npm 2.

**Comment by gdborton** [comment]
Not supporting 20 is blocking coverage on untested files @airbnb since previous to 20 the coverage is instrumented on the parent worker. We definitely want to update, so hopefully they'll cut a release in the next few days... I'll try to check against w/e the master sha is to verify it's been fixed.

**Comment by gdborton** [comment]
> I'd be very interested to see what that PR looks like; it'd be ideal to add v20 support in a minor instead of a major.

It's icky but...
https://www.npmjs.com/package/semver

```javascript
const version = require('jest/package.json').version;
const semver = require('semver');
if (semver.satisfies(version, '18 || 19')) {
  // ...
} else {
  // ...
}
```

**Comment by ljharb** [comment]
ooh, oof. i was hoping for something more "feature test" and less "user agent sniff".

What about something like `Suite.prototype.afterAll.call([1], 2)[0] === 2`?

**Comment by gdborton** [comment]
I'm going to be totally honest... I have no idea what that snippet is attempting to do.

**Comment by ljharb** [comment]
It's attempting to determine if `afterAll` is doing `unshift` or `push` - which is the change you made. It's using `.call` to set the `this` value to an object containing an array, and then `afterAll` mutates that array - in jest < 20, it pushes `2` onto the end, in >= 20, it unshifts it onto the front - so after that, we can check `arr` to determine whether it's `[1, 2]` or `[2, 1]`.

**Comment by ljharb** [comment]
Per discussion, the only way to support this is with a version check, or with a conditional require, so let's do the version check, cut a minor release, and then immediately drop support for < 20 and cut a major.

(pending the npm2 bugfix)

**Comment by gdborton** [comment]
Closing this in favor of #9 which preserves backward compatibility.

**Pull request closed without merging**
